"""Report the provenance of the Large Offset fixture measurements.

Every cue *timing* the committed corpus uses is a real observation captured
from the production cache for the confirmed case, Dexter S08E04:

  target   Dexter.s8e04.Scar.tissue.1080p.BluRay.TrueHD5.1.AVC-PiR8.mkv
           560 cues, 14.57s .. 2971.40s, first dialogue 107.54s
  reference compatible BluRay reference, 562 cues, 10.71s .. 2852.90s,
           first dialogue 10.71s  ->  a measured ~96.6s displacement

THIS SCRIPT NO LONGER WRITES FIXTURES.

The repository is public, and the dialogue in those cache files is third-party
subtitle text that cannot be redistributed. The committed fixtures therefore
carry the measured timings with SYNTHETIC dialogue, regenerated by:

    python tools/build_synthetic_large_offset_fixtures.py

This tool is kept because it is the provenance record: run it to re-measure the
original inputs on a machine that still has them and confirm the timings the
committed corpus is built on. It prints only measurements, never subtitle text.
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from app.services.subtitle_matcher import parse_srt_cues  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
CACHE = ROOT / "subs_cache"
REFERENCES = CACHE / "references"

TARGET_SOURCE = CACHE / "74a34c232d159f8b.srt"
REFERENCE_SOURCE = (
    REFERENCES / "tt0773262_8_4_PiR8_v2_f80bfa730f1a046f_t6349da3c0192e384_subsource_edition.srt"
)
WRONG_EPISODE_SOURCE = sorted(REFERENCES.glob("tt0773262_8_5_*_subsource_edition.srt"))[0]


def timestamp(ms: int) -> str:
    ms = max(0, int(ms))
    hours, ms = divmod(ms, 3_600_000)
    minutes, ms = divmod(ms, 60_000)
    seconds, ms = divmod(ms, 1000)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{ms:03d}"


def render(cues: list[tuple[int, int, str]]) -> str:
    blocks = [
        f"{index + 1}\n{timestamp(start)} --> {timestamp(end)}\n{text}"
        for index, (start, end, text) in enumerate(cues)
    ]
    return "\n\n".join(blocks) + "\n"


def load(path: pathlib.Path) -> list[tuple[int, int, str]]:
    return parse_srt_cues(path.read_text(encoding="utf-8", errors="replace"))


def shifted(
    cues: list[tuple[int, int, str]], offset_ms: float, drift_ms_per_minute: float = 0.0
) -> list[tuple[int, int, str]]:
    """Translate a whole timeline, optionally with a progressive component."""
    moved: list[tuple[int, int, str]] = []
    for start, end, text in cues:
        delta = offset_ms + drift_ms_per_minute * (start / 60_000.0)
        moved.append((start + int(delta), end + int(delta), text))
    return moved


def main() -> int:
    target = load(TARGET_SOURCE)
    reference = load(REFERENCE_SOURCE)
    wrong_episode = load(WRONG_EPISODE_SOURCE)

    # The transforms the committed corpus encodes, reported so the synthetic
    # regeneration can be checked against the measurements it was derived from.
    drifting = shifted(reference, 0.0, drift_ms_per_minute=300.0)
    pivot = len(reference) // 2
    different_cut = [
        (s, e, t) if i < pivot else (s + 600_000, e + 600_000, t)
        for i, (s, e, t) in enumerate(reference)
    ]

    def describe(label: str, cues) -> None:
        print(f"  {label:<26} cues={len(cues):<5} first_ms={cues[0][0]:<8} "
              f"last_ms={cues[-1][1]}")

    print("Large-offset fixture provenance (measured; no text is printed):")
    describe("target", target)
    describe("reference", reference)
    describe("negative_different_cut", different_cut)
    describe("negative_wrong_episode", wrong_episode)
    describe("negative_drifting", drifting)
    describe("negative_insufficient", reference[:3])
    describe("valid_constant_offset", shifted(reference, 3_650))
    print()
    print("Timings only. Dialogue is NOT written anywhere; the public corpus is")
    print("regenerated with tools/build_synthetic_large_offset_fixtures.py.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
